server:
  servlet:
    context-path: /
  port: 8080

rec:
  db:
    calendar:
      master:
        jdbc-url: jdbc:mysql://localhost:3307/calendar?useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: calendar
        password: calendar
        driver-class-name: com.mysql.cj.jdbc.Driver
        pool-name: calendar
        minimum-idle: 50
        maximum-pool-size: 100

wx:
  appid: wx94e2e35a5dc3361b
  app-secret: f20f47cc352e983fbac63d9ccbdd4ee5